name: CI/pida
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: ./
        with:
          distro: Ubuntu-24.04
      - run: cat /etc/os-release && uname -a
        shell: wsl-run {0}
