name: CI/pida
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          # update WSL, download & install Ubuntu-24.04
          wsl --set-default-version 2; wsl --update; wsl --status;
          if ('Ubuntu-24.04' -eq 'none') {
            Write-Output 'Skipping distro installation...'
            return
          }
          $distros = (Invoke-RestMethod -Uri https://raw.githubusercontent.com/microsoft/WSL/refs/heads/master/distributions/DistributionInfo.json).Distributions
          if ($distros.Name -notcontains 'Ubuntu-24.04') {
            Write-Output 'Invalid distro: Ubuntu-24.04'
            Write-Output 'The value should be one of the following:'
            wsl --list --online
            exit 1
          }
          # github runner does support windows arm64 runners, so we don't need to check the architecture
          $distroDownloadUrl = $distros.Where({ $_.Name -eq 'Ubuntu-24.04' }).Amd64PackageUrl
          Set-Location $env:GITHUB_WORKSPACE\..\.. # don't download in $env:GITHUB_WORKSPACE
          $filename = "Ubuntu-24.04$([System.IO.Path]::GetExtension($distroDownloadUrl))"
          Write-Output 'Downloading and installing the distro...'
          Invoke-WebRequest -Uri $distroDownloadUrl -OutFile $filename
          if ($filename.EndsWith('.appxbundle', [System.StringComparison]::OrdinalIgnoreCase)) {
            Expand-Archive -Path $filename -DestinationPath .\AppxBundle
            Remove-Item -Path $filename -Force # cleanup so we don't fill up the disk unnecessarily
            $filename = (Get-ChildItem -Path .\AppxBundle -Filter *x64*).FullName
          }
          Expand-Archive -Path $filename -DestinationPath .\
          Remove-Item -Path .\AppxBundle -Recurse -Force -ErrorAction SilentlyContinue # cleanup
          # exclude the extra splash and setup exe files that come with "ubuntu" and "ubuntu-22.04" distros
          $distroExe = (Get-ChildItem -Path . -Filter *.exe).Where({ $_.Name -notmatch 'splash|setup' }).FullName
          & $distroExe install --root
          if ('${{ inputs.enable-systemd }}' -eq 'true') {
            Write-Output 'Enabling systemd support...'
            @'
          [boot]
          systemd=true
          '@ | Out-File -FilePath .\wsl.conf -Encoding utf8
            wsl --distribution Ubuntu-24.04 --cd $(Get-Location) cp wsl.conf /etc/wsl.conf
            Write-Output 'Restarting WSL...'
            wsl --shutdown
            # https://learn.microsoft.com/en-us/windows/wsl/wsl-config#the-8-second-rule-for-configuration-changes
            # although the documentation says 8 seconds, we wait for 10 seconds to be safe
            Start-Sleep -Seconds 10
          }
          Write-Output 'Running command to test the installation...'
          Write-Output '-> cat /etc/os-release'
          wsl --distribution Ubuntu-24.04 cat /etc/os-release # print the distro info
          # add a wrapper script to run commands inside wsl easily using run.shell in github workflows
          @'
          @echo off
          FOR /F "usebackq tokens=*" %%F IN (`wsl wslpath '%~1'`) DO SET wslpath=%%F
          wsl -d Ubuntu-24.04 sed -i 's/\r$//' %wslpath%
          wsl -d Ubuntu-24.04 --cd %GITHUB_WORKSPACE% bash --noprofile --norc -eo pipefail %wslpath%
          '@ | Out-File -FilePath $env:RUNNER_TEMP\wsl-run.bat -Encoding utf8
          $env:RUNNER_TEMP >> $env:GITHUB_PATH
        shell: pwsh
      - run: cat /etc/os-release && uname -a
        shell: wsl-run {0}
